ai_context_version: 1.0

# Dieses Repo ist Teil des Heimgewebes.
# Systemweiter Kontext durch Heimgeist:
#   metarepo/ai-contexts/heimgeist.ai-context.yml

system_context:
  heimgeist: "../metarepo/ai-contexts/heimgeist.ai-context.yml"

project:
  name: chronik
  summary: Event ingest and processing hub.
  role: central_event_store
  primary_language: python
  visibility: internal

dependencies:
  internal:
    - name: contracts
      relationship: uses
      interface:
        - json_schema
        - proto
  external:
    - name: fastapi
    - name: uvicorn
    - name: filelock
    - name: prometheus-fastapi-instrumentator
    - name: slowapi

architecture:
  entrypoints:
    - app.py
  key_paths:
    - path: app.py
      purpose: HTTP ingest + validation + API
    - path: storage.py
      purpose: File I/O + domain validation + locking
    - path: clients/rust/chronik_producer/
      purpose: Rust client library
  data_flow:
    input: HTTP POST /v1/ingest
    processing: JSON validation + domain sanitization
    output: local JSONL files (append-only)

conventions:
  branching: "main, feature/*, hotfix/*"
  commit_prefix: "chronik"
  ci_platform: github_actions

documentation:
  adr: docs/adr/
  runbook: docs/runbook.md
  openapi: docs/openapi.yaml

ai_guidance:
  do:
    - validate payloads against contracts (if applicable)
    - use structured logging via ExtraFormatter
    - ensure safe file operations (no path traversal)
  dont:
    - modify generated JSONL files manually
    - bypass sanitize_domain validation
